version: '3'
services:
  app:
    build: 
      context: .
      args:
        NODE_ENV: ${NODE_ENV}
    ports:
      - "${SERVER_PORT}:3000"
    env_file:
      - .env
    networks:
      - backend
networks:
  backend:
    driver: "bridge"